name: CI & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Check out repository
        uses: actions/checkout@v3

      # 2) Set up QEMU and Buildx (for cross-platform builds, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3) Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4) Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spoton:latest

      # 5) (Optional) Add output or notify step here
      # - name: Notify
      #   run: echo "Image pushed: ${{ secrets.DOCKERHUB_USERNAME }}/spoton:latest"
